NewSpring/crete

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> chore: Adds Pull Request Template

src/server.js
=> Fixes Internal Server Error

src/server.js
=> fixes error

src/data/prayers/schema.js
This just gives us the outline. Will resolve in another PR.
Pull up the playground and inspect the docs. Make sure everything looks right.
---
=> chore: Adds Schema for Paginated Prayers

src/bugsnag.js, src/server.js
=> chore: Better Error Handling

.travis.yml, package.json
This will publish our production schema to Engine so we can monitor deprecations.
¯\\\_(ツ)\_/¯
---
=> chore: Publishes Production Schema to Engine in CI

src/data/auth/data-source.js
Attaches bad cookies to the error message
If I knew, we wouldn't be doing this...
---
=> chore: Captures cookies and sends them to bugsnag

src/bugsnag.js, src/server.js
This fixes a potential 500 error and also shows errors on the console again.
Make an error happen and make sure it shows up in the console.
---
=> chore: Show errors in console

.travis.yml, loadtests/userFeed.lua, package.json, src/bugsnag.js, src/data/auth/data-source.js, src/data/prayers/schema.js, src/server.js
=> Merge Develop to Staging

src/server.js
=> chore: Fixes Bugsnag Reporting

package.json, scripts/translate.js
Gives us a way to quickly go between Rock IDs and Apollos IDs
`SECRET=<secret> yarn translate <ID>`
---
=> chore: Adds Script to Translate Data IDs

src/data/prayers/data-source.js
=> Beta API Release

.travis.yml
The unnecessary argument is breaking Travis. It's defined in `src/server.js`
---
=> chore: Fixes Travis deploy

src/data/content-items/data-source.js
Don't need this. We never used it.
Make sure images still show up in the `userFeed` query
---
=> chore: Removes unnecessary image code

.travis.yml, src/data/content-items/data-source.js
=> Beta Release

src/data/live/data-source.js
=> fix: Fixes Live API

src/data/live/data-source.js
=> fix: Puts the Livestream API Back Correctly

config.yml
This PR adds the CSB translation to our app.
---
=> chore: Added the CSB Translation

.mergify.yml
This PR gets `mergify` working.
---
=> chore: Get Mergify Working

src/data/prayers/data-source.js
This PR fixes prayer notifications so that they work correctly.
Pray for a prayer and make sure that the "PrayerNotificationSent" interaction get written correctly. Then check that the triggered workflow actually gets triggered when it should.
---
=> fix: Make Prayer Notifications Work

package.json, src/index.js, yarn.lock
=> chore: Adds Appdynamics Dashboard

src/index.js
=> move appdynamics config to top and change some values

.travis.yml, package.json
=> chore: Adds New Start Command

.github/workflows/tests.yml, package.json, src/data/prayers/__tests__/__snapshots__/data-source.test.js.snap, src/data/prayers/__tests__/data-source.test.js, src/data/prayers/data-source.js, src/data/prayers/resolver.js, yarn.lock
Changes saved prayers to return empty cursor instead of `null`
With no saved prayers, run this:
```
{
prayerFeed(type:SAVED) {
totalCount
edges {
node {
id
}
}
}
}
```
---
=> fix: Fixes Empty List Queries

src/data/prayers/__tests__/__snapshots__/resolver.test.js.snap, src/data/prayers/__tests__/resolver.test.js, src/data/prayers/resolver.js, src/data/prayers/schema.js
I started making updates to the prayer API and noticed it was getting very bloated so I thought we could simplify a little.
Run through the five simplified queries. I also added test coverage.
---
=> chore: Simplifies Prayer API

package.json, src/index.js, yarn.lock
=> chore: Adds Rookout

.github/workflows/lint.yml, .github/workflows/loadtest.yml, .github/workflows/unittest.yml, loadtests/tests.yml, loadtests/userFeed.lua, package.json, yarn.lock
This will allow us to write integration tests using a much simpler interface than `wrk`. We can use this for CI tests after pushing to staging and check that everything is still working properly.
`ARTILLERY_TARGET_URL=https://apollos-ns-staging-herokuapp-com.global.ssl.fastly.net/ AUTH_TOKEN=<your auth token> yarn loadtest`
---
=> chore: Adds Artillery Integration Tests

src/data/index.js
=> perf: Disable Cache to fix memory leak

src/data/prayers/resolver.js, src/server.js
=> chore: Adds Time to Errors

package.json, src/data/index.js, src/server.js, yarn.lock
=> chore: Adds Redis Cache to Server

src/server.js
=> fix: Fixes Redis

package.json, scripts/leakdump.js, yarn.lock
=> chore: Adds script to capture memory dump to S3

apollos.json, package.json, yarn.lock
Not sure what's in here.
Boot it.
---
=> perf: Upgrades to Apollos 1.4.1

src/data/prayers/data-source.js
Stops adding sessions to interactions. This is a problem for us because the sessions may have been cleared in the DB causing errors.
Pray for a prayer.
---
=> fix: Stops adding sessions to interactions

package.json, yarn.lock
Simply removes some packages that we used to use for housekeeping and CI stuff that we don't use anymore.
Boot up the server.
---
=> chore: Removes Unused Packages

src/server.js
Adds back in some server side bug tracking
Not sure if we can in dev
---
=> chore: Adds Bugsnag Tracking

config.yml, package.json, yarn.lock
This PR updates the `data-connector-rock` package. This package update should fix the problem we see where someone in a signed out state can still browse around the app. Now if you're in a signed out state it should take you back to sign in.
🤷‍♂️ 
Vincent said that we could edit the `data-source` of `data-connector-rock` in our `node_modules` folder to throw an error after this line (https://github.com/ApollosProject/apollos-apps/blob/master/packages/apollos-data-connector-rock/src/auth/data-source.js#L32). So after that line add something like `throw new AuthenticationError('cookie fail');`. But I couldn't make it work. So ... in my mind, either it doesn't work or I couldn't test it correctly. But everything in the app seemed to work just fine. So I'd test that.
---
> The purpose of a PR …
=> fix: Fixes Signed Out State

src/data/content-items/data-source.js
This PR fixes the sort order of content items to correctly look at the `Order` property.
Change up the order of some content items on a study and then run the app and make sure that the items in the horizontal content slider show up in the correct order.
Feel free to test other content channels as well to make sure it sorts correctly everywhere. 
---
=> fix: Fixed Content Item Sort Order

config.yml
=> chore: New RESI/Living as One Stream Values

config.yml
Shows the latest devotional as the featured item at the top of the Read tab
=> chore: Corrects Read Tab Content

src/data/index.js, src/data/index.postgres.js, src/data/pass.js
=> null out paskiturl
